valid event
make new event
valid event
Internal Server Error: /staff/churchevent/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/russell/Projects/whuc/whuc/church/views.py", line 110, in staff
    thiseventType = request.POST['eventType']
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/utils/datastructures.py", line 301, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'eventType'"
Internal Server Error: /staff/churchevent/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/russell/Projects/whuc/whuc/church/views.py", line 110, in staff
    thiseventType = request.POST['eventType']
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/utils/datastructures.py", line 301, in __getitem__
    raise MultiValueDictKeyError(repr(key))
MultiValueDictKeyError: "'eventType'"
valid event
valid event
valid event
valid event
could not find this event
valid event
Internal Server Error: /church/home/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/russell/Projects/whuc/whuc/whuc/urls.py", line 15, in <module>
    )  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT+'/upload')
NameError: name 'static' is not defined
Internal Server Error: /church/home/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/russell/Projects/whuc/whuc/whuc/urls.py", line 16, in <module>
    )  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT+'/upload')
NameError: name 'settings' is not defined
Internal Server Error: /church/home/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 99, in get_response
    resolver_match = resolver.resolve(request.path_info)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 337, in resolve
    for pattern in self.url_patterns:
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 365, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/urlresolvers.py", line 360, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/Users/russell/Projects/whuc/whuc/whuc/urls.py", line 16, in <module>
    )  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT+'/upload')
NameError: name 'settings' is not defined
Not Found: /files/upload/LetterForUBC_2.pdf
Internal Server Error: /staff/churchevent/
Traceback (most recent call last):
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/russell/Virtualenvs/whuc/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/russell/Projects/whuc/whuc/church/views.py", line 138, in staff
    churcheventForm = ChurchEventForm(instance=churchevent)
UnboundLocalError: local variable 'churchevent' referenced before assignment
valid event
valid event
could not find this event
valid event
valid event
